### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by BlobTheKat** [Mint-Midori/test#1]
Is this account @mint still in use?

**Comment by Mint-Midori** [comment]
Yes, I am using this account.

**Comment by BlobTheKat** [comment]
It's probably not hard to imagine how/why I found you.
I am developing a language. That language is called **Mint**, and I am looking to make a github organization. Would you be willing to free up your username for my project?
- You don't have to transfer or delete your account, github allows changing username for free

You may reply privately, my email is `blob.kat@hotmail.com`
Thanks

**Comment by Mint-Midori** [comment]
I understand. I will now change my username.

**Comment by BlobTheKat** [comment]
> I understand. I will now change my username.

Thank you 👍 

https://github.com/mint you're kidding someone else has it 😭
